# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from enum import Enum


class ImportMode(Enum):

    no_force = "NoForce"
    force = "Force"


class SkuName(Enum):

    classic = "Classic"
    basic = "Basic"
    standard = "Standard"
    premium = "Premium"


class SkuTier(Enum):

    classic = "Classic"
    basic = "Basic"
    standard = "Standard"
    premium = "Premium"


class ProvisioningState(Enum):

    creating = "Creating"
    updating = "Updating"
    deleting = "Deleting"
    succeeded = "Succeeded"
    failed = "Failed"
    canceled = "Canceled"


class DefaultAction(Enum):

    allow = "Allow"
    deny = "Deny"


class Action(Enum):

    allow = "Allow"


class PasswordName(Enum):

    password = "password"
    password2 = "password2"


class RegistryUsageUnit(Enum):

    count = "Count"
    bytes = "Bytes"


class PolicyStatus(Enum):

    enabled = "enabled"
    disabled = "disabled"


class TrustPolicyType(Enum):

    notary = "Notary"


class WebhookStatus(Enum):

    enabled = "enabled"
    disabled = "disabled"


class WebhookAction(Enum):

    push = "push"
    delete = "delete"
    quarantine = "quarantine"
    chart_push = "chart_push"
    chart_delete = "chart_delete"


class TokenCertificateName(Enum):

    certificate1 = "certificate1"
    certificate2 = "certificate2"


class TokenPasswordName(Enum):

    password1 = "password1"
    password2 = "password2"


class Status(Enum):

    enabled = "enabled"
    disabled = "disabled"
